---
- name: Hello World - nmstate Network Configuration
  hosts: all
  gather_facts: yes
  vars:
    network_state:
      dns-resolver:
        config:
          server:
          - 192.168.122.1
          search:
          - rrajesh-na.ibmlowe.csb
      routes:
        config:
          - destination: 0.0.0.0/0
            next-hop-address: 192.168.122.1
            next-hop-interface: enp1s0
      interfaces:
        - name: enp1s0              # Replace with your interface name
          type: ethernet
          state: up
          ipv4:
            enabled: true
            dhcp: false           # We'll set a static IP
            address:
              - ip: 192.168.122.194
                prefix-length: 24
          ipv6:
            enabled: true
            dhcp: false
            autoconf: false
            address:
              - ip: fe80::5054:ff:fe1c:bc66
                prefix-length: 64

  tasks:
    - name: Apply network configuration using nmstate
      include_role:
        name: linux-system-roles.network
    - name: Verify network configuration
      debug:
        msg: "Network configuration applied successfully!"
